spring:
  application:
    name: spring-notification-service
  mail:
    host: localhost
    port: 1025
    username: admin
    password: 1234
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/notification-service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: NotificationDto:com.poojithairosha.notification.dto.NotificationDto

twilio:
  account-sid: ACCOUNT_SID
  auth-token: AUTH_TOKEN
  from-number: FROM_NUMBER
  from-wanumber: whatsapp:FROM_NUMBER
server:
  port: 8090
